name: SudokuJS
uuid: e0daeba0-6c60-4854-b1ec-0cdca8b754f2
project:
  - name: SodokuJS
    type: web-static
    packageManager: yarn
    webpack: true
    distDirectory: build
    buildCommand: yarn build