name: SudokuJS
uuid: e0daeba0-6c60-4854-b1ec-0cdca8b754f2
directory:
projects:
  - name: SodokuJS
    directory:
    type: web-static
    packageManager: yarn
    distDirectory: build
    buildCommand: yarn build